"""Add user profile fields for job matching

Revision ID: f7c86b6d5eaa
Revises: 1c52754aeba6
Create Date: 2025-08-30 15:59:27.734799

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f7c86b6d5eaa'
down_revision = '1c52754aeba6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('experience_years', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('salary_expectation', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('preferred_job_types', sa.JSON(), nullable=True))
    op.add_column('users', sa.Column('preferred_remote_types', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'preferred_remote_types')
    op.drop_column('users', 'preferred_job_types')
    op.drop_column('users', 'salary_expectation')
    op.drop_column('users', 'experience_years')
    # ### end Alembic commands ###